apiVersion: v1
kind: Service
metadata:
  name: grr-webhook
  labels:
    app: grr-webhook
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: grr-webhook
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
